SETTINGS:
  gpu: True
  experiment_path: /home/esandstroem/scratch-second/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/src/RoutedFusion/workspace/routing # path where the logging is done and the models are saved.
MODEL:
  contraction: 64
  depth: 1
  n_output_channels: 2
  normalization: False
LOSS:
  name: gradweighted + uncertainty # gradweighteduncertainty or gradweighted + uncertainty or uncertainty or VNL + gradweighted + uncertainty or VNL + gradweighteduncertainty
  crop_fraction: 0.
  vmin: 0.05
  vmax: 12.3
  weight_scale: 10. # only relevant if the gradweighted term is used
  lmbda: 0.06
  completion: True # If completion is True, all pixels incur a loss, while, if it is false, on those with a valid input value incur a loss.
TRAINING:
  train_batch_size: 2
  train_shuffle: True
  val_batch_size: 2
  val_shuffle: False
  n_epochs: 1000
TESTING:
  test_batch_size: 1
  test_shuffle: False
  model_path: /home/esandstroem/scratch-second/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/src/RoutedFusion/workspace/routing/201230-204843/model/best.pth.tar
  output_path:
OPTIMIZATION:
  lr: 1.e-05
  rho: 0.95
  eps: 1.e-07
  momentum: 0.9
  weight_decay: 0.01
  accumulate: True
  accumulation_steps: 16
  alternate: False
  alternate_steps: 5
DATA:
  fusion_strategy: routingNet # not used but needed because of replica.py
  data_load_strategy: max_depth_diversity # max_depth_diversity, hybrid - not used, but needed here because of replica.py
  intensity_grad: False # weather to load the grayscale image and its gradient and feed to the routing network
  root_dir: /home/esandstroem/scratch-second/opportunistic_3d_capture/data/habitat/replica/manual
  dataset: Replica
  input: multidepth # mono_depth, stereo_depth, tof_depth, multidepth
  target: depth_gt
  resx: 512
  resy: 512
  focalx: 256 # focal length of intrinsic matrix
  focaly: 256
  train_scene_list: /home/esandstroem/scratch-second/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/src/RoutedFusion/lists/replica/train.txt
  val_scene_list: /home/esandstroem/scratch-second/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/src/RoutedFusion/lists/replica/val.txt
  test_scene_list: /home/esandstroem/scratch-second/opportunistic_3d_capture/Erik_3D_Reconstruction_Project/src/RoutedFusion/lists/replica/test_small.txt
  init_value: 0.1 # truncation distance
  truncation_strategy: standard # standard, artificial or none